"use client";
import { useEffect, useState } from "react";
import { ProductCard } from "@/components/product-card";
import type { Product } from "@/lib/types";
const categories = ["전체", "초보자", "계절 추천", "관찰"];
export function Catalog({ featured = false }: { featured?: boolean }) {
  const [items, setItems] = useState<Product[]>([]), [query, setQuery] = useState(""), [category, setCategory] = useState(""), [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(async () => { setState("loading"); try { const params = new URLSearchParams(); if (query) params.set("q", query); if (category) params.set("category", category); const response = await fetch(`/api/products?${params}`, { signal: controller.signal }); if (!response.ok) throw new Error(); const data = await response.json() as Product[]; setItems(featured ? data.slice(0, 3) : data); setState("ready"); } catch (error) { if ((error as Error).name !== "AbortError") setState("error"); } }, featured ? 0 : 180); return () => { controller.abort(); clearTimeout(timer); }; }, [query, category, featured]);
  if (featured) return state === "loading" ? <div className="grid">{[1,2,3].map((id) => <div className="skeleton" key={id}/>)}</div> : state === "error" ? <div className="error">추천 상품을 불러오지 못했습니다. 새로고침해 다시 시도해 주세요.</div> : <div className="grid">{items.map((item) => <ProductCard key={item.id} product={item}/>)}</div>;
  return <><div className="toolbar"><input className="field" aria-label="상품 검색" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="키트 이름 또는 설명으로 검색" />{categories.map((name) => <button key={name} className={`chip ${category === (name === "전체" ? "" : name) ? "active" : ""}`} onClick={() => setCategory(name === "전체" ? "" : name)}>{name}</button>)}</div>{state === "loading" ? <div className="grid">{[1,2,3,4].map((id) => <div className="skeleton" key={id}/>)}</div> : state === "error" ? <div className="state"><p>목록을 불러오지 못했습니다.</p><button className="button" onClick={() => location.reload()}>다시 시도</button></div> : items.length ? <div className="grid">{items.map((item) => <ProductCard key={item.id} product={item}/>)}</div> : <div className="state"><p>조건에 맞는 결과가 없습니다. 다른 조건으로 찾아보세요.</p><button className="button subtle" onClick={() => { setQuery(""); setCategory(""); }}>필터 초기화</button></div>}</>;
}
